name: The Negation of Negation
url: http://thenegation.com
author: Vehbi Sinan Tunalioglu
markdown: redcarpet
pygments: true
paginate: 5
permalink: /blog/:year/:month/:day/:title.html
excerpt_separator: <!-- more -->