name: "Build and Deploy Website"

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: "Build Website"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout main"
        uses: "actions/checkout@v3.0.0"
      - name: "Install Nix"
        uses: "cachix/install-nix-action@v22"
        with:
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Build Website"
        run: |
          nix develop --command bash -c "tailwindcss --minify --input styles/main.css --output static/styles/main.css && zola build"
      - name: "Fix Permissions of Website Artifacts"
        run: |
          chmod -c -R +rX "public/" | while read -r line; do
            echo "::warning title=Invalid file permissions automatically fixed::${line}"
          done
      - name: "Upload Website"
        uses: "actions/upload-pages-artifact@v2"
        with:
          path: "public/"

  deploy:
    name: "Deploy Website"
    needs: "build"
    permissions:
      pages: "write"
      id-token: "write"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Deploy to GitHub Pages"
        id: "deployment"
        uses: "actions/deploy-pages@v2"
